### ISSUE TITLE
 Review establishing-the-analysis-zone

### ISSUE THREAD

**Issue by msoltadeo** [worldbank/alternative-data-for-crisis#73]
@abrilr1604 Could you review the material for the class establishing-the-analysis-zone. 
- [ ] Review the class as if you were a student from [here](https://reimagined-disco-g6q6ny1.pages.github.io/notebooks/establishing-the-analysis-zone/establishing-the-analysis-zone.html). You do not need to understand/review the whole code. 
- [ ] Download the data using the information from the notebook.
- [ ] Run the notebook and check that everything is running smoothly.
- [ ] The data is also stored [here](https://worldbankgroup.sharepoint.com/:f:/t/DevelopmentDataPartnershipCommunity-WBGroup/EktlWsKcMCtCopL20xDZFoEBoEW1JD5CBe3BXIpbk-W1NQ?email=arodriguez12%40worldbank.org&e=F90hRI). This is a back-up in case the day of the course the link for downloading is not working. Please check that the notebook also runs with this data.
- [ ] Do the practice and provide feedback. Was it difficult? Was it useful to understand the concepts? 
- [ ] Create a list of suggestions if needed. For example, parts you did not understand, parts that could be improved

**Comment by abrilr1604** [comment]
@msoltadeo  some comments about this issue:

- The Eurostat link didn’t work for me as it gave a "not found" error. I had to download the data from the sharepoint instead.

![image](https://github.com/user-attachments/assets/933b1d78-e33f-4359-870a-d6b51971c831)

- The code in the notebook works perfectly.

- I found two typos:

1.  "Antoher consideration for defining the analysis zone is whether..." – Misspelled word: **Another**
2. "## Excercises" Misspelled word: **Exercises**

- The practice was easy, even for someone like me who doesn’t have much experience with this type of analysis. Just by reading the notebook, one can complete the practice without any issues.

![image](https://github.com/user-attachments/assets/821203fa-75fe-46ed-8e89-6fbe9b36974a)

- Maybe a suggestion would be to include a requirements.txt file or a list of the libraries needed to run the notebook. For example, when I tried running the first block of code it gave me an error because matplotlib and mapclassify were required to use the explore() method

![Captura de pantalla 2024-11-26 165624](https://github.com/user-attachments/assets/3b1a01ff-0c84-4db5-b3df-7bab8028cfd8)

**Comment by msoltadeo** [comment]
@abrilr1604 can you try downloading the files from this [link](https://gisco-services.ec.europa.eu/distribution/v2/nuts/geojson/). Instead of downloading the files using request you should:
1. right click over the link
2. save link as
3. save the geojson

If that works, can you:

- [ ] Update the link for downloading
- [ ] Fix the typos
- [ ] In the cell that imports the packages, add the following code commented. 
```
!pip install matplotlib mapclassify
```
- [ ] Make a PR with this changes

**Comment by msoltadeo** [comment]
PR #82 merged.
