### ISSUE TITLE
Global Course - Crisis | Review mapping-and-monitoring-conflict

### ISSUE THREAD

**Issue by msoltadeo** [worldbank/alternative-data-for-crisis#76]
@abrilr1604 similar to what you did for #73 

- [ ] Review the specific class as if you were a student, [here]

- [ ] Review the class as if you were a student from [here](https://reimagined-disco-g6q6ny1.pages.github.io/notebooks/mapping-and-monitoring-extent/mapping-and-monitoring-conflict.html). You do not need to understand/review the whole code.
- [ ]  Download the data using the information from the notebook.
- [ ] Run the notebook and check that everything is running smoothly.
- [ ] The data is also stored [here](https://worldbankgroup.sharepoint.com/:f:/t/DevelopmentDataPartnershipCommunity-WBGroup/EktlWsKcMCtCopL20xDZFoEBoEW1JD5CBe3BXIpbk-W1NQ?email=arodriguez12%40worldbank.org&e=F90hRI). This is a back-up in case the day of the course the link for downloading is not working. Please check that the notebook also runs with this data.
- [ ] Do the practice and provide feedback. Was it difficult? Was it useful to understand the concepts?
- [ ]  Create a list of suggestions if needed. For example, parts you did not understand, parts that could be improved

**Comment by abrilr1604** [comment]
@msoltadeo a few comments: 

1.  In the 'Data Analysis' section, the data is being read from a csv file, but this only works if you’ve downloaded the data using the data export tool. In my case, i pulled the data directly from the API and stored it in the _data_api_ variable, which caused an error when I ran this part of the code because the _data_ variable wasn't defined.

![image](https://github.com/user-attachments/assets/5603727d-43ca-411c-923e-ae6816ee4d8d)

Also, when using the API all the data types are set to objects.. So, when I try to filter the rows for the years 2022, 2023, and 2024 as integers, I get an empty dataframe. If I fix it by treating the years as strings, I run into another problem because the date format is different (year-month-day).

![image](https://github.com/user-attachments/assets/70c1ca7a-f0fb-4d80-83c4-3ee4d17887ab)

So, the data is different when pulled through the API compared to downloading it from the data export tool. 
I thought a possible fix would be to save the API data as a csvand then read it, but that doesn't solve the issues with the data types or the date format.

2. I don't know why I can't see any outputs from bokeh. It doesn't give any errors, so it’s probably me.

![image](https://github.com/user-attachments/assets/b53176bb-9196-4cab-bf13-6e32bea72924)

3. In the 'Map of density of events by administrative level 3' section, where can I get the file: syr_admbnda_adm3_uncs_unocha.json? If it's supposed to be downloaded from any of the pages in section [3.4.1.1. Sources to get Administrative boundaries](https://reimagined-disco-g6q6ny1.pages.github.io/notebooks/establishing-the-analysis-zone/establishing-the-analysis-zone.html)  then it might be helpful to mention that in the Jupyter notebook

4. A suggestion would be to import `warnings `to avoid these types of outputs, what do you think ? (same with `!pip` before importing libraries that require installation) 

```
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)
```

![image](https://github.com/user-attachments/assets/9bf20048-6e23-43bc-b3a4-fd2c331830ca)

5. I haven't resolved the practice yet, I'll let you know when i do it !

**Comment by msoltadeo** [comment]
@abrilr1604, thank you for the feedback. I will answer below:
Issue 1: Solved and merged into develop. 
Issue 2: Let's have a quick call to try to fix it and understand why that can happen. Also, did you wait a minute? Sometimes it take a little bit for it to plot
Issue 3: Sent you the file already
Issue 4: Thank you! I incorporated it

**Comment by msoltadeo** [comment]
@abrilr1604, I saw your email, thank you for sharing your notebook. Could you make a PR that creates a new folder named `solutions_to_practice` in the path `alternative-data-for-crisis/notebooks/` and upload your notebook with the name `practice-resolution-mapping-and-monitoring-conflict`. 
About the item that you could not solve, it is understandable as you had not done that before. Do not worry about it. If you are curious, I can show you how to do it :nerd_face: 

Thank you :rocket:

**Comment by abrilr1604** [comment]
@msoltadeo PR done! once item 4 is solved, I'll take a look to see how it's done! :)

**Comment by msoltadeo** [comment]
@abrilr1604, I updated the practice and the notebook with the solutions. Please review it and if you agree, you can go ahead and close the issue.

**Comment by abrilr1604** [comment]
issue closed!
