### ISSUE TITLE
Global Course - Crisis | Review mapping exposure section

### ISSUE THREAD

**Issue by msoltadeo** [worldbank/alternative-data-for-crisis#85]
@abrilr1604 similar to what you did for #73 but in this case you will be reviewing a whole section. 
- [ ] Review the classes for Mapping Exposure, both for infrastructure and population, [here](https://reimagined-disco-g6q6ny1.pages.github.io/README.html)
- [ ] Download the data using the information from the notebook.
- [ ] Run the notebook and check that everything is running smoothly.
- [ ] The data is also stored [here](https://worldbankgroup.sharepoint.com/:f:/t/DevelopmentDataPartnershipCommunity-WBGroup/EktlWsKcMCtCopL20xDZFoEBoEW1JD5CBe3BXIpbk-W1NQ?email=arodriguez12%40worldbank.org&e=F90hRI). This is a back-up in case the day of the course the link for downloading is not working. Please check that the notebook also runs with this data.
- [ ] Do the practice and provide feedback. Was it difficult? Was it useful to understand the concepts? 
- [ ] Create a list of suggestions if needed. For example, parts you did not understand, parts that could be improved

**Comment by abrilr1604** [comment]
@msoltadeo:

- The code runs perfectly and everything is explained clearly
- There are a few typos that I’ll fix in the next PR.
- Some pages are not working: 
1. Section 12.5.1: https://overturemaps.org/overture-maps-foundation-releases-first-world-wide-open-map-dataset/
![image](https://github.com/user-attachments/assets/7f1304eb-32b5-4a39-9ce8-36323c49600a)

2. Section 12.5.2: https://github.com/OvertureMaps/schema/blob/main/task-force-docs/places/overture_categories.csv

![image](https://github.com/user-attachments/assets/00c5e96e-602d-4cc7-bcec-f25bd0cefdc9)

- When i click on this link it just takes me to the same page:
![image](https://github.com/user-attachments/assets/1912d9f6-2f04-4898-a1fe-0b69e84edd06)


- I did the practice, it was tricky to find a region that worked with Microsoft Building Footprints. Most of the regions I tried gave me the error "QuadKey not found in dataset," but I finally found one in Angola that worked. I’ll upload the notebook once I can finish the Population part because the sjoin is taking too long  and  thepython kernel keeps restarting

**Comment by msoltadeo** [comment]
@abrilr1604 Thank you for catching that!!! 
I attach the new links:
replace this:https://overturemaps.org/overture-maps-foundation-releases-first-world-wide-open-map-dataset/
with this: https://docs.overturemaps.org/guides/buildings/#14/32.58453/-117.05154/0/60
replace this: https://github.com/OvertureMaps/schema/blob/main/task-force-docs/places/overture_categories.csv
with this: https://github.com/OvertureMaps/schema/blob/main/docs/schema/concepts/by-theme/places/overture_categories.csv

About the practice:
I was just planning for students to plot a part of the datasets on the same maps. Do you need to do a sjoin? Let me know if I can help you out and speed it up.

**Comment by abrilr1604** [comment]
@msoltadeo hi Sol, I have updated the links and fixed some typos in the notebooks. I'm about to push a new branch to the repository so we can merge it.

I ran out of memory while executing this cell in the 'mapping-exposure-population' notebook because the 6 files are too large. So I couldn't change the sjoin_nearest to sjoin as we discussed yesterday.

```
# load datasets into a single dataframe to perform the spatial join only once
dfs = []
for d in datasets:
    data = pd.read_csv(path + d).set_index(['latitude', 'longitude'])
    dfs.append(data)
df = pd.concat(dfs, axis = 1)
df.reset_index(inplace = True)
df_gdf = convert_to_gdf(df, 'latitude', 'longitude', crs = "EPSG:4326")
```

Do you think you could make that change and run the code for the Meta part again?  If you do, please add this to avoid the warning:  _/home/sol/venv/lib/python3.10/site-packages/geopandas/array.py:403: UserWarning: Geometry is in a geographic CRS. Results from 'sjoin_nearest' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation._

```
import warnings
warnings.filterwarnings('ignore')
```

do you think other students might have the same memory issue when running the notebook?

**Comment by msoltadeo** [comment]
@abrilr1604, I can make the change, please make the PR and I will pull you branch and make the change there.

It is an issue that is not running for you. It happened to me as well, but I increased the swap memory of my machine and it worked. I can comment that code so we avoid running it during the course.
However, let's try to see if we can sort it out for you. Are you using colab? Do you use Windows?

**Comment by abrilr1604** [comment]
@msoltadeo PR done. I'm using VS code and windows.  I haven't tried running it on Colab, I'll try to run it there 🙂

**Comment by msoltadeo** [comment]
@abrilr1604, I was asking about Colab because it might have less resources than your personal laptop. 
Also, since we are going to use proprietary data for the creation of the notebooks, we cannot use Colab. So, to avoid confusions, better to avoid Colab

**Comment by msoltadeo** [comment]
@abrilr1604, Can you confitm that you reviewed the [mapping-exposure-population](https://reimagined-disco-g6q6ny1.pages.github.io/notebooks/mapping-exposure/mapping-exposure-population.html) and it is ok? I do not see it in the PR
The same question for the [mapping-exposure-infrastructure](https://reimagined-disco-g6q6ny1.pages.github.io/notebooks/mapping-exposure/mapping-exposure-infrastructure-main.html) and for [the introduction](https://reimagined-disco-g6q6ny1.pages.github.io/notebooks/mapping-exposure/mapping-exposure-intro.html).

**Comment by msoltadeo** [comment]
@abrilr1604 is going to:
1. For the population notebook, correct typos, change sjoin_nearest for sjoin
2. Solve teh practice
3. Make a PR with the two files.

**Comment by abrilr1604** [comment]
@msoltadeo PR done! I reviewed all the notebooks in this section. If you agree with the practice resolution, we can close the issue

**Comment by abrilr1604** [comment]
@msoltadeo will verify everything works fine before merging

**Comment by msoltadeo** [comment]
@abrilr1604 , PR was merged. Closing the issue
